version: '2'
services:
  magneto-app:
    image: jhorber95/magneto:1.0
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://magneto-postgresql:5432/mercado
      - APP_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
#    network_mode: host
  magneto-postgresql:
    extends:
      file: postgresql.yml
      service: magneto-postgresql
