apiVersion: apps/v1
kind: Deployment
metadata:
  name: magneto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magneto
      version: 'v1'
  template:
    metadata:
      labels:
        app: magneto
        version: 'v1'
    spec:
      containers:
        - name: magneto-app
          image: jhorber95/magneto:2.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://magneto-postgresql.default.svc.cluster.local:5432/mercado
            - name: SPRING_DATASOURCE_USERNAME
              value: mercado
            - name: SPRING_DATASOURCE_PASSWORD
              value: mercado
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
