apiVersion: v1
kind: Service
metadata:
  name: magneto
  namespace: default
  labels:
    app: magneto
spec:
  selector:
    app: magneto
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
